# Whether this GitHub repo is for a CC-led engineering project
engineering_project: false
# Name of the repository/project in English
english_name: CC signals
# All technologies used, sorted
technologies: AI Preferences, Markdown
# Whether this repository should be featured on the CC Open Source site's "Projects" page
featured: false
# Slack channel name (optional key)
# slack:
